[package]
name = "sentinel-infrastructure"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
argon2.workspace = true
chrono.workspace = true
base64.workspace = true
getrandom.workspace = true
hmac.workspace = true
sentinel-application = { path = "../application" }
sentinel-domain = { path = "../domain" }
sha2.workspace = true
sqlx.workspace = true
subtle.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true
