[package]
name = "sentinel-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
chrono.workspace = true
sentinel-api-contract = { path = "../../crates/api-contract" }
sentinel-application = { path = "../../crates/application" }
sentinel-domain = { path = "../../crates/domain" }
sentinel-infrastructure = { path = "../../crates/infrastructure" }
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
http-body-util.workspace = true
tower.workspace = true
